version: "3.8"

services:
  database:
    image: postgres:14.6
    container_name: rate_database
    environment:
      - POSTGRES_USER=rate
      - POSTGRES_PASSWORD=rate
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
