version: "3.8"

services:
  rate:
    image: ghcr.io/zoedsoupe/rate:dev
    command: ["mix", "dev"]
    container_name: rate
    ports:
      - 4000:4000
    depends_on:
      - database
    env_file:
      - .env.test
    volumes:
      - .:/src
    environment:
      MIX_ENV: dev
    stdin_open: true
    tty: true

  database:
    image: postgres:14.6
    container_name: rate_database
    environment:
      - POSTGRES_USER=zoedsoupe
      - POSTGRES_PASSWORD=""
      - POSTGRES_DB=rate_dev
    ports:
      - 5432:5432
    volumes:
      - .postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U zoedsoupe -d rate_dev" ]
      interval: 5s
      timeout: 2s
      retries: 1
